# Generated by Django 4.1.1 on 2022-09-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='location',
            new_name='locationDisplayName',
        ),
        migrations.AddField(
            model_name='drink',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
    ]
